package reporter

import (
	"fmt"

	"github.com/go-pdf/fpdf"
)

// ExportPDF generates a PDF report based on the analysis results
func ExportPDF(report Report, filename string) error {
	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.AddPage()

	// Header
	pdf.SetFont("Arial", "B", 20)
	pdf.SetTextColor(0, 51, 102)
	pdf.Cell(190, 15, "Archive Duplicate Finder Report")
	pdf.Ln(15)

	// Summary Section
	pdf.SetFont("Arial", "B", 14)
	pdf.SetTextColor(0, 0, 0)
	pdf.Cell(190, 10, "Analysis Summary")
	pdf.Ln(10)

	pdf.SetFont("Arial", "", 11)
	pdf.Cell(50, 8, "Timestamp:")
	pdf.Cell(140, 8, report.Timestamp)
	pdf.Ln(8)
	pdf.Cell(50, 8, "Total Files Analyzed:")
	pdf.Cell(140, 8, fmt.Sprintf("%d", report.TotalFiles))
	pdf.Ln(8)
	pdf.Cell(50, 8, "Identical Size Groups:")
	pdf.Cell(140, 8, fmt.Sprintf("%d", len(report.SizeGroups)))
	pdf.Ln(8)
	pdf.Cell(50, 8, "Similar Name Pairs:")
	pdf.Cell(140, 8, fmt.Sprintf("%d", len(report.SimilarPairs)))
	pdf.Ln(8)
	pdf.Cell(50, 8, "Analysis Duration:")
	pdf.Cell(140, 8, fmt.Sprintf("%.2fs", report.AnalysisDuration))
	pdf.Ln(15)

	// Identical Size Groups Section
	if len(report.SizeGroups) > 0 {
		pdf.SetFont("Arial", "B", 14)
		pdf.SetFillColor(230, 230, 230)
		pdf.CellFormat(190, 10, "Files with Identical Size", "1", 1, "L", true, 0, "")

		for i, group := range report.SizeGroups {
			pdf.SetFont("Arial", "I", 11)
			pdf.Cell(190, 8, fmt.Sprintf("Group %d - Size: %s", i+1, formatBytes(group.Size)))
			pdf.Ln(8)

			pdf.SetFont("Arial", "", 10)
			for _, file := range group.Files {
				pdf.SetTextColor(100, 100, 100)
				pdf.Cell(10, 6, "[-] ")
				pdf.SetTextColor(0, 0, 0)
				pdf.Cell(180, 6, file.Name)
				pdf.Ln(6)
			}
			pdf.Ln(4)

			if pdf.GetY() > 250 {
				pdf.AddPage()
			}
		}
		pdf.Ln(10)
	}

	// Similar Name Pairs Section
	if len(report.SimilarPairs) > 0 {
		pdf.SetFont("Arial", "B", 14)
		pdf.SetFillColor(230, 230, 230)
		pdf.CellFormat(190, 10, "Files with Similar Names", "1", 1, "L", true, 0, "")

		for i, pair := range report.SimilarPairs {
			pdf.SetFont("Arial", "I", 11)
			pdf.Cell(190, 8, fmt.Sprintf("Pair %d - Similarity: %.1f%%", i+1, pair.Similarity))
			pdf.Ln(8)

			pdf.SetFont("Arial", "", 10)
			pdf.Cell(90, 6, pair.File1.Name)
			pdf.Cell(10, 6, " <-> ")
			pdf.Cell(90, 6, pair.File2.Name)
			pdf.Ln(6)

			pdf.SetTextColor(100, 100, 100)
			pdf.Cell(190, 6, fmt.Sprintf("Sizes: %s vs %s", formatBytes(pair.File1.Size), formatBytes(pair.File2.Size)))
			pdf.SetTextColor(0, 0, 0)
			pdf.Ln(8)

			if pdf.GetY() > 250 {
				pdf.AddPage()
			}
		}
	}

	// Footer
	pdf.SetY(-15)
	pdf.SetFont("Arial", "I", 8)
	pdf.SetTextColor(128, 128, 128)
	pdf.CellFormat(0, 10, fmt.Sprintf("Page %d | Generated by Archive Duplicate Finder", pdf.PageNo()), "", 0, "C", false, 0, "")

	return pdf.OutputFileAndClose(filename)
}

func formatBytes(bytes int64) string {
	const unit = 1024
	if bytes < unit {
		return fmt.Sprintf("%d B", bytes)
	}
	div, exp := int64(unit), 0
	for n := bytes / unit; n >= unit; n /= unit {
		div *= unit
		exp++
	}
	return fmt.Sprintf("%.1f %cB", float64(bytes)/float64(div), "KMGTPE"[exp])
}
